<?php

namespace RecipeBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DictIngredientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictIngredientsRepository extends EntityRepository
{
}
