<?php

namespace RecipeBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecondaryIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecondaryIngredientRepository extends EntityRepository
{
}
